apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: barista
  namespace: airport
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: barista
---

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: barista
  namespace: airport
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/n3wscott/kubecon/airport/cmd/airport/
            env:
              - name: AIRPORT_ROLE
                value: "barista"
              - name: BROKER
                value: "http://outbound-broker.airport.svc.cluster.local/"
              - name: MEMCACHE_SERVERS
                value: "memcached.airport.svc.cluster.local:11211"
              - name: SINK_ACCESS_KEY_NAME
                valueFrom:
                  secretKeyRef:
                    name: airport-amqp
                    key: sink_access_key_name
              - name: SINK_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: airport-amqp
                    key: sink_access_key
