apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: amqp-ext
  namespace: airport
spec:
  hosts:
  - <ampq host url>
  ports:
  - number: <port number>
    name: amqp
    protocol: TCP
  location: MESH_INTERNAL